config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'dashboards/index'
  root 'dashboards#index'
  post 'dashboards/mailchimp_signup'

  namespace :admin do
    resources :adjectives, except: [:show]
    resources :companies, except: [:show]
    resources :nouns, except: [:show]
    resources :organizations, except: [:show]
    resources :users, except: [:new, :create, :show]
    resources :verbs, except: [:show]
  end
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  include Sorted
  include PgSearch::Model

  pg_search_scope :search_by_company_info,
                  against: %i[word],
                  using: {
                    tsearch: {
                      prefix: true,
                      any_word: true,
                      dictionary: 'english'
                    }
                  }
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_action :set_company, except: %i[index new create]

  def index
    @companies = searched_scope(Company.all, 'word', 'search_by_company_info')
    @companies = @companies.order(sort_column('email') + " " + sort_direction) if params[:column].present?
    @pagy, @companies = pagy(@companies)
  end

  def edit; end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to admin_companies_path, notice: 'Create successful'
    else
      render :new
    end
  end

  def update
    @company.update(company_params)
    redirect_to admin_companies_path, notice: 'Update successful'
  end

  def destroy
    @company.destroy
    redirect_to admin_companies_path, notice: 'Delete successful'
  end

  private

    def company_params
      params.require(:company).permit(:word)
    end

    def set_company
      @company = Company.find(params[:id])
    end

    def sortable_columns
      %w[word]
    end

    def filter_param_keys
      %i[search column direction word]
    end
end

app/helpers/admin/companies_helper.rb
# frozen_string_literal: true

module Admin
  module CompaniesHelper
  end
end

app/views/admin/companies/_form.html.erb
<%= form_for [:admin, @company] do |f| %>
  <div class='container'>
    <%= render 'partials/form_errors', object: @company %>
  </div>

  <div class='row'>
    <div class='col text-end'>
      <%= f.label 'Word', class: 'form-label' %>
    </div>
    <div class='col text-start'>
      <%= f.text_field :word, class: 'form-control' %>
    </div>
  </div>

  <div class='row'>
    <div class='col text-center mt-3'>
      <%= f.submit 'Create', class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/admin/companies/create.html.erb
<h1>Admin::Companies#create</h1>
<p>Find me in app/views/admin/companies/create.html.erb</p>

app/views/admin/companies/destroy.html.erb
<h1>Admin::Companies#destroy</h1>
<p>Find me in app/views/admin/companies/destroy.html.erb</p>

app/views/admin/companies/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col text-center panel-title'>
      <h3>Edit a Company</h3>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/admin/companies/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col text-center'>
      <h3 class='panel-title'>COMPANIES</h3>
    </div>
  </div>

  <div class='row'>
    <div class='col text-center'>
      <%= render 'partials/search_form', url: admin_companies_path %>
    </div>
  </div>
  <%= render 'partials/clear_search', path: admin_companies_path %>


  <table class='table table-hover'>
    <thead>
      <tr>
        <th scope='col'><%= sort_link 'word' %></th>
      </tr>
    </thead>

    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td scope='row'><%= company.word %></td>
          <td><%= link_to 'Edit', edit_admin_company_path(company) %></td>
          <td><%= link_to 'Delete', admin_company_path(company), method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'partials/pagy_menu' %>

app/views/admin/companies/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col text-center panel-title'>
      <h3>Create a New Company</h3>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/admin/companies/update.html.erb
<h1>Admin::Companies#update</h1>
<p>Find me in app/views/admin/companies/update.html.erb</p>