config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'dashboards/index'
  root 'dashboards#index'
  post 'dashboards/mailchimp_signup'

  namespace :admin do
    resources :adjectives, except: [:show]
    resources :companies, except: [:show]
    resources :nouns, except: [:show]
    resources :organizations, except: [:show]
    resources :users, except: [:new, :create, :show]
    resources :verbs, except: [:show]
  end
end

app/views/partials/_clear_search.html.erb
<div class='row'>
  <div class='col text-center'>
    <% if params[:column].present? || params[:search].present? %>
      <%= link_to 'Remove column sorting', path %>
    <% else %>
      <%= link_to 'Remove column sorting', path, class: 'hidden' %>
    <% end %>
  </div>
</div>

app/views/partials/_example_sentence.html.erb
<div class='row navbar-light bg-light'>
  <div class='col text-center text-wrap'>
    <p class='fs-6 fw-lighter'>We are #{article_and_noun(company)} who #{verbs} #{noun} for #{adj}.</p>
  </div>
</div>

app/views/partials/_footer.html.erb
<div id='footer-block'>
  <div class='left-margin'>
    <div class='row'>
      <div class='col text-start'>
        <%= link_to "https://www.publicover.co", target: "_blank" do %>
          <% image_tag('pubco_logo.png', id: 'pubco-logo', class: 'margin-left') %>
        <% end %>
      </div>
      <div class='col text-end right-margin align-self-center'>
        <%= link_to "https://www.instagram.com/publicoverandco/", target: "_blank" do %>
          <% image_tag('ig_logo.png') %>
        <% end %>
        &nbsp
        <%= link_to "https://www.linkedin.com/company/publicover/?originalSubdomain=de", target: "_blank" do %>
          <% image_tag('li_logo.png') %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_form_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <p class='text-center'>
      <%= pluralize(object.errors.count, "error") %> prohibited
      this article from being saved:
    </p>
    <% object.errors.full_messages.each do |msg| %>
      <li><center><%= msg %></li>
    <% end %>
  </div>
<% end %>

app/views/partials/_header.html.erb
<nav class='navbar navbar-expand-lg navbar-light bg-light'>
  <div class='container'>
    <%= link_to 'Bad Pitch Generator', root_path, class: 'navbar-brand' %>
    <button class='navbar-toggler'
            type='button'
            data-bs-toggle='collapse'
            data-bs-target='#navbarSupportedContent'
            aria-controls='navbarSupportedContent'
            aria-expanded='false'
            aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav me-auto mb-2 mb-lg-0'>
        <li class='nav-item'>
          <%= link_to 'Users', admin_users_path, class: 'nav-link' %>
        </li>

        <li class='nav-item dropdown'>
          <a class="nav-link dropdown-toggle
                    <%= active_if(admin_adjectives_path) %>
                    <%= active_if(new_admin_adjective_path) %>"
                     href='#' id='navbarDropdown' role='button'
                     data-bs-toggle='dropdown' aria-expanded='false'>
            Adjectives
          </a>
          <ul class='dropdown-menu' aria-labelledby='navbarDropdown'>
            <li><%= link_to 'All Adjectives', admin_adjectives_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'New Adjective', new_admin_adjective_path, class: 'dropdown-item' %></li>
          </ul>
        </li>

        <li class='nav-item dropdown'>
          <a class="nav-link dropdown-toggle
                    <%= active_if(admin_companies_path) %>
                    <%= active_if(new_admin_company_path) %>"
                     href='#' id='navbarDropdown' role='button'
                     data-bs-toggle='dropdown' aria-expanded='false'>
            Companies
          </a>
          <ul class='dropdown-menu' aria-labelledby='navbarDropdown'>
            <li><%= link_to 'All Companies', admin_companies_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'New Company', new_admin_company_path, class: 'dropdown-item' %></li>
          </ul>
        </li>

        <li class='nav-item dropdown'>
          <a class="nav-link dropdown-toggle
                    <%= active_if(admin_nouns_path) %>
                    <%= active_if(new_admin_noun_path) %>"
                     href='#' id='navbarDropdown' role='button'
                     data-bs-toggle='dropdown' aria-expanded='false'>
            Nouns
          </a>
          <ul class='dropdown-menu' aria-labelledby='navbarDropdown'>
            <li><%= link_to 'All Nouns', admin_nouns_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'New Noun', new_admin_noun_path, class: 'dropdown-item' %></li>
          </ul>
        </li>

        <li class='nav-item dropdown'>
          <a class="nav-link dropdown-toggle
                    <%= active_if(admin_organizations_path) %>
                    <%= active_if(new_admin_organization_path) %>"
                     href='#' id='navbarDropdown' role='button'
                     data-bs-toggle='dropdown' aria-expanded='false'>
            Organizations
          </a>
          <ul class='dropdown-menu' aria-labelledby='navbarDropdown'>
            <li><%= link_to 'All Organizations', admin_organizations_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'New Organization', new_admin_organization_path, class: 'dropdown-item' %></li>
          </ul>
        </li>

        <li class='nav-item dropdown'>
          <a class="nav-link dropdown-toggle
                    <%= active_if(admin_verbs_path) %>
                    <%= active_if(new_admin_verb_path) %>"
                     href='#' id='navbarDropdown' role='button'
                     data-bs-toggle='dropdown' aria-expanded='false'>
            Verbs
          </a>
          <ul class='dropdown-menu' aria-labelledby='navbarDropdown'>
            <li><%= link_to 'All Verbs', admin_verbs_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'New Verb', new_admin_verb_path, class: 'dropdown-item' %></li>
          </ul>
        </li>

      </ul>

      <ul class='navbar-nav ms-auto'>
        <span class='nav-item me-auto'>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </span>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_pagy_menu.html.erb
<div class='container'>
  <div class='row'>
    <div class='col pagy-middle'>
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>

app/views/partials/_search_form.html.erb
<%= form_for :search, url: url, method: :get do |f| %>
  <%= f.text_field :search, value: params[:search], name: :search, placeholder: 'SHOW ME' %>
  <%= f.submit 'Search'%>
<% end %>