config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'dashboards/index'
  root 'dashboards#index'
  post 'dashboards/mailchimp_signup'

  namespace :admin do
    resources :adjectives, except: [:show]
    resources :companies, except: [:show]
    resources :nouns, except: [:show]
    resources :organizations, except: [:show]
    resources :users, except: [:new, :create, :show]
    resources :verbs, except: [:show]
  end
end

app/models/noun.rb
# frozen_string_literal: true

class Noun < ApplicationRecord
  include Sorted
  include PgSearch::Model

  pg_search_scope :search_by_noun_info,
                  against: %i[word],
                  using: {
                    tsearch: {
                      prefix: true,
                      any_word: true,
                      dictionary: 'english'
                    }
                  }
end

app/controllers/admin/nouns_controller.rb
class Admin::NounsController < ApplicationController
  before_action :set_noun, except: %i[index new create]

  def index
    @nouns = searched_scope(Noun.all, 'word', 'search_by_noun_info')
    @nouns = @nouns.order(sort_column('email') + " " + sort_direction) if params[:column].present?
    @pagy, @nouns = pagy(@nouns)
  end

  def edit; end

  def new
    @noun = Noun.new
  end

  def create
    @noun = Noun.new(noun_params)
    if @noun.save
      redirect_to admin_nouns_path, notice: 'Create successful'
    else
      render :new
    end
  end

  def update
    @noun.update(noun_params)
    redirect_to admin_nouns_path, notice: 'Update successful'
  end

  def destroy
    @noun.destroy
    redirect_to admin_nouns_path, notice: 'Delete successful'
  end

  private

    def noun_params
      params.require(:noun).permit(:word)
    end

    def set_noun
      @noun = Noun.find(params[:id])
    end

    def sortable_columns
      %w[word]
    end

    def filter_param_keys
      %i[search column direction word]
    end
end

app/helpers/admin/nouns_helper.rb
# frozen_string_literal: true

module Admin
  module NounsHelper
  end
end

app/views/admin/nouns/_form.html.erb
<%= form_for [:admin, @noun] do |f| %>
  <div class='container'>
    <%= render 'partials/form_errors', object: @noun %>
  </div>

  <div class='row'>
    <div class='col text-end'>
      <%= f.label 'Word', class: 'form-label' %>
    </div>
    <div class='col text-start'>
      <%= f.text_field :word, class: 'form-control' %>
    </div>
  </div>

  <div class='row'>
    <div class='col text-center mt-3'>
      <%= f.submit 'Create', class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/admin/nouns/create.html.erb
<h1>Admin::Nouns#create</h1>
<p>Find me in app/views/admin/nouns/create.html.erb</p>

app/views/admin/nouns/destroy.html.erb
<h1>Admin::Nouns#destroy</h1>
<p>Find me in app/views/admin/nouns/destroy.html.erb</p>

app/views/admin/nouns/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col text-center panel-title'>
      <h3>Edit a Noun</h3>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/admin/nouns/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col text-center'>
      <h3 class='panel-title'>NOUNS</h3>
    </div>
  </div>

  <div class='row'>
    <div class='col text-center'>
      <%= render 'partials/search_form', url: admin_nouns_path %>
    </div>
  </div>
  <%= render 'partials/clear_search', path: admin_nouns_path %>


  <table class='table table-hover'>
    <thead>
      <tr>
        <th scope='col'><%= sort_link 'word' %></th>
      </tr>
    </thead>

    <tbody>
      <% @nouns.each do |noun| %>
        <tr>
          <td scope='row'><%= noun.word %></td>
          <td><%= link_to 'Edit', edit_admin_noun_path(noun) %></td>
          <td><%= link_to 'Delete', admin_noun_path(noun), method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'partials/pagy_menu' %>

app/views/admin/nouns/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col text-center panel-title'>
      <h3>Create a New Noun</h3>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/admin/nouns/update.html.erb
<h1>Admin::Nouns#update</h1>
<p>Find me in app/views/admin/nouns/update.html.erb</p>