config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'dashboards/index'
  root 'dashboards#index'
  post 'dashboards/mailchimp_signup'

  namespace :admin do
    resources :adjectives, except: [:show]
    resources :companies, except: [:show]
    resources :nouns, except: [:show]
    resources :organizations, except: [:show]
    resources :users, except: [:new, :create, :show]
    resources :verbs, except: [:show]
  end
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  include Sorted
  include PgSearch::Model

  pg_search_scope :search_by_org_info,
                  against: %i[word],
                  using: {
                    tsearch: {
                      prefix: true,
                      any_word: true,
                      dictionary: 'english'
                    }
                  }

  enum conjunction: {
    thing: 0,
    person: 1
  }
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController
  before_action :set_organization, except: %i[index new create]

  def index
    @organizations = searched_scope(Organization.all, 'word', 'search_by_org_info')
    @organizations = @organizations.order(sort_column('email') + " " + sort_direction) if params[:column].present?
    @pagy, @organizations = pagy(@organizations)
  end

  def edit; end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to admin_organizations_path, notice: 'Create successful'
    else
      render :new
    end
  end

  def update
    @organization.update(organization_params)
    redirect_to admin_organizations_path, notice: 'Update successful'
  end

  def destroy
    @organization.destroy
    redirect_to admin_organizations_path, notice: 'Delete successful'
  end

  private

    def organization_params
      params.require(:organization).permit(:word)
    end

    def set_organization
      @organization = Organization.find(params[:id])
    end

    def sortable_columns
      %w[word]
    end

    def filter_param_keys
      %i[search column direction word]
    end
end

app/helpers/admin/organizations_helper.rb
# frozen_string_literal: true

module Admin
  module OrganizationsHelper
  end
end

app/views/admin/organizations/_form.html.erb
<%= form_for [:admin, @organization] do |f| %>
  <div class='container'>
    <%= render 'partials/form_errors', object: @organization %>
  </div>

  <div class='row'>
    <div class='col text-end'>
      <%= f.label 'Word', class: 'form-label' %>
    </div>
    <div class='col text-start'>
      <%= f.text_field :word, class: 'form-control' %>
    </div>
  </div>

  <div class='row'>
    <div class='col text-center mt-3'>
      <%= f.submit 'Create', class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/admin/organizations/create.html.erb
<h1>Admin::Organizations#create</h1>
<p>Find me in app/views/admin/organizations/create.html.erb</p>

app/views/admin/organizations/destroy.html.erb
<h1>Admin::Organizations#destroy</h1>
<p>Find me in app/views/admin/organizations/destroy.html.erb</p>

app/views/admin/organizations/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col text-center panel-title'>
      <h3>Edit an Organization</h3>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/admin/organizations/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col text-center'>
      <h3 class='panel-title'>ORGANIZATIONS</h3>
    </div>
  </div>

  <div class='row'>
    <div class='col text-center'>
      <%= render 'partials/search_form', url: admin_organizations_path %>
    </div>
  </div>
  <%= render 'partials/clear_search', path: admin_organizations_path %>


  <table class='table table-hover'>
    <thead>
      <tr>
        <th scope='col'><%= sort_link 'word' %></th>
      </tr>
    </thead>

    <tbody>
      <% @organizations.each do |organization| %>
        <tr>
          <td scope='row'><%= organization.word %></td>
          <td><%= link_to 'Edit', edit_admin_organization_path(organization) %></td>
          <td><%= link_to 'Delete', admin_organization_path(organization), method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'partials/pagy_menu' %>

app/views/admin/organizations/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col text-center panel-title'>
      <h3>Create a New Organization</h3>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/admin/organizations/update.html.erb
<h1>Admin::Organizations#update</h1>
<p>Find me in app/views/admin/organizations/update.html.erb</p>